name: Windows x86

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PREFIX: i686-w64-mingw32

jobs:
   build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v4.2.2

     - name: Update package list
       run: sudo apt-get update 

     - name: Install Dependencies
       run: sudo apt-get install -y gcc-mingw-w64-i686 binutils-mingw-w64-i686

     - name: Build SRB2
       run: make -C src/ --keep-going  -j$(nproc) MINGW=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.5.0
       with:
        name: srb2fusionadvance-windows-x86
        path: |
          bin/
          src/comptime.h 
